"""
Script per aggiornare il database part_numbers_db.xlsx con i nuovi part numbers
dai file BOM di esempio.
"""

import pandas as pd
from datetime import datetime
from pathlib import Path

# Importa il modulo database
from pn_lookup import PartNumberDatabase

# =========================================================================
# DATI DEI PART NUMBERS DA AGGIUNGERE
# =========================================================================

# Mappa colonne BOM -> database
def bom_component_to_db_data(comp):
    """Converte una riga BOM in dizionario compatibile con il database."""
    pn = comp[1]  # Supplier Part Number
    supplier = comp[0]  # Supplier Name
    category = comp[6]  # Category of product

    # Determina frontend/backend country in base ai plant
    plant1_country = comp[18] if len(comp) > 18 else None
    plant2_country = comp[20] if len(comp) > 20 else None

    frontend = plant1_country if plant1_country else ''
    backend = plant2_country if plant2_country else plant1_country

    # OS Type
    os_raw = comp[13] if len(comp) > 13 else None
    os_map = {
        'Baremetal': 'Baremetal',
        'Linux': 'Linux',
        'Windows': 'Windows',
        'FreeRTOS': 'FreeRTOS',
        'RTOS': 'RTOS',
        'None': 'Baremetal',
    }
    os_type = os_map.get(os_raw, 'Baremetal') if os_raw else ''

    # Memory type
    embedded = comp[11] if len(comp) > 11 else None
    external = comp[12] if len(comp) > 12 else None
    if embedded == 'Y' and external == 'No':
        memory_type = 'Embedded'
    elif external == 'Yes':
        memory_type = 'External'
    else:
        memory_type = ''

    # Wireless protocol
    wireless = comp[14] if len(comp) > 14 else None

    return {
        'Supplier Name': supplier,
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': category,
        'Country of Manufacturing Plant 1': plant1_country or '',
        'Country of Manufacturing Plant 2': plant2_country or '',
        'Country of Manufacturing Plant 3': comp[22] if len(comp) > 22 else '',
        'Country of Manufacturing Plant 4': comp[24] if len(comp) > 24 else '',
        'Supplier Lead Time (weeks)': int(comp[8]) if comp[8] else 0,
        'Proprietary (Y/N)**': comp[9] if len(comp) > 9 else 'N',
        'Commodity (Y/N)*': comp[7] if len(comp) > 7 else 'Y',
        'Stand-Alone Functional Device (Y/N)': comp[2] if len(comp) > 2 else 'Y',
        'Weeks to qualify': int(comp[16]) if len(comp) > 16 and comp[16] else 0,
        'Unit Price ($)': float(comp[4]) if len(comp) > 4 and comp[4] else 0.0,
        'Specify Certification/Qualification': comp[15] if len(comp) > 15 else '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': comp[3] if len(comp) > 3 else '',
        # v3.0 fields
        'Frontend_Country': frontend,
        'Backend_Country': backend,
        'Technology_Node': comp[17] if len(comp) > 17 else '',
        'Plant_1_Name': comp[19] if len(comp) > 19 else '',
        'Plant_2_Name': comp[21] if len(comp) > 21 else '',
        'Plant_3_Name': comp[23] if len(comp) > 23 else '',
        'Plant_4_Name': comp[25] if len(comp) > 25 else '',
        'EMS_Used': comp[26] if len(comp) > 26 and comp[26] == 'Yes' else 'N',
        'EMS_Name': comp[27] if len(comp) > 27 else '',
        'EMS_Location': comp[28] if len(comp) > 28 else '',
        'SW_Code_Size_KB': int(comp[10]) if len(comp) > 10 and comp[10] else 0,
        'Memory_Type': memory_type,
        'OS_Type': os_type,
        'Wireless_Protocol': wireless or '',
        # v3.1 fields
        'EOL_Status': comp[35] if len(comp) > 35 else 'Active',
        'Number_of_Alternative_Sources': int(comp[36]) if len(comp) > 36 and comp[36] else 0,
        'Supplier_Financial_Health': comp[37] if len(comp) > 37 else 'A',
        'MTBF_Hours': int(comp[38]) if len(comp) > 38 and comp[38] else 0,
        'Automotive_Grade': comp[39] if len(comp) > 39 else '',
        'Last_Price_Increase_Pct': int(comp[40]) if len(comp) > 40 and comp[40] else 0,
        'Allocation_Status': comp[41] if len(comp) > 41 else 'Normal',
        'Package_Type': comp[42] if len(comp) > 42 else '',
    }


# =========================================================================
# DATI COMPLETI DEI COMPONENTI (hardcoded per precisione)
# =========================================================================

# CLIENTI
CLIENTS = [
    {'Client_ID': 'ADAS_AUTO', 'Client_Name': 'Automotive ADAS Manufacturer', 'Default_Run_Rate': 3000},
    {'Client_ID': 'IOT_INDUST', 'Client_Name': 'Industrial IoT Solutions', 'Default_Run_Rate': 8000},
]

# Lista completa dei componenti con tutti i campi database
COMPONENTS_DB = [
    # ========== ADAS BOARD COMPONENTS ==========
    {
        'Part Number': 'S32K344',
        'Supplier Name': 'NXP',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'MCU',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': 'Thailand',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 22,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 28,
        'Unit Price ($)': 8.50,
        'Specify Certification/Qualification': 'AEC-Q100, ISO 26262 ASIL-D',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'malaysia',
        'Technology_Node': '40nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'NXP (ATMC)',
        'Plant_3_Name': 'NXP',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 1024,
        'Memory_Type': 'Embedded',
        'OS_Type': 'Baremetal',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 500000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 8,
        'Allocation_Status': 'Normal',
        'Package_Type': 'BGA',
    },
    {
        'Part Number': 'S32G274A',
        'Supplier Name': 'NXP',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'MPU',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 26,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 36,
        'Unit Price ($)': 28.00,
        'Specify Certification/Qualification': 'AEC-Q100, ISO 26262 ASIL-B',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'PMIC PF5024, LPDDR4 MT53E256M32D1DS',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'china',
        'Technology_Node': '16nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'JCET',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 4096,
        'Memory_Type': 'External',
        'OS_Type': 'Linux',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 0,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 400000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 15,
        'Allocation_Status': 'Constrained',
        'Package_Type': 'FCBGA',
    },
    {
        'Part Number': 'PF5024',
        'Supplier Name': 'NXP',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Power',
        'Country of Manufacturing Plant 1': 'USA',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 20,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 24,
        'Unit Price ($)': 5.80,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'S32G274A MPU',
        'Frontend_Country': 'usa',
        'Backend_Country': 'malaysia',
        'Technology_Node': '130nm',
        'Plant_1_Name': 'NXP',
        'Plant_2_Name': 'NXP (ATMC)',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 0,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 600000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 5,
        'Allocation_Status': 'Normal',
        'Package_Type': 'QFN',
    },
    {
        'Part Number': 'EyeQ5H',
        'Supplier Name': 'Mobileye (Intel)',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'MPU',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'Taiwan',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 32,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 48,
        'Unit Price ($)': 55.00,
        'Specify Certification/Qualification': 'AEC-Q100, ISO 26262 ASIL-B',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'LPDDR4 MT53E256M32, NOR Flash MX25U25645G',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'taiwan',
        'Technology_Node': '7nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'ASE',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 8192,
        'Memory_Type': 'External',
        'OS_Type': 'Linux',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 0,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 350000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Allocated',
        'Package_Type': 'FCBGA',
    },
    {
        'Part Number': 'MT53E256M32D1DS-046',
        'Supplier Name': 'Micron',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Memory',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 18,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 16,
        'Unit Price ($)': 6.50,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'S32G274A MPU, EyeQ5H Vision Processor',
        'Frontend_Country': 'japan',
        'Backend_Country': 'china',
        'Technology_Node': '12nm',
        'Plant_1_Name': 'Micron',
        'Plant_2_Name': 'Micron',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': 'External',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 200000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 30,
        'Allocation_Status': 'Constrained',
        'Package_Type': 'BGA',
    },
    {
        'Part Number': 'MX25U25645G',
        'Supplier Name': 'Macronix',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Memory',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'Taiwan',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 14,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 12,
        'Unit Price ($)': 2.80,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'taiwan',
        'Technology_Node': '45nm',
        'Plant_1_Name': 'Macronix',
        'Plant_2_Name': 'Macronix',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'B',
        'MTBF_Hours': 300000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 10,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SOP',
    },
    {
        'Part Number': '88Q2112-A2-NNP2I000',
        'Supplier Name': 'Marvell',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Transceiver',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 24,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 20,
        'Unit Price ($)': 4.20,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'malaysia',
        'Technology_Node': '28nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'ASE',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 64,
        'Memory_Type': 'Embedded',
        'OS_Type': 'Baremetal',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 450000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 12,
        'Allocation_Status': 'Constrained',
        'Package_Type': 'QFN',
    },
    {
        'Part Number': 'TPS65263-1QRGZRQ1',
        'Supplier Name': 'Texas Instruments',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Power',
        'Country of Manufacturing Plant 1': 'USA',
        'Country of Manufacturing Plant 2': 'Germany',
        'Country of Manufacturing Plant 3': 'Taiwan',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 12,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 10,
        'Unit Price ($)': 3.50,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'usa',
        'Backend_Country': 'germany',
        'Technology_Node': '65nm',
        'Plant_1_Name': 'TI',
        'Plant_2_Name': 'TI',
        'Plant_3_Name': 'TSMC',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 700000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 3,
        'Allocation_Status': 'Normal',
        'Package_Type': 'QFN',
    },
    {
        'Part Number': 'SMI230',
        'Supplier Name': 'Bosch Sensortec',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Sensor',
        'Country of Manufacturing Plant 1': 'Germany',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 16,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 14,
        'Unit Price ($)': 3.80,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'germany',
        'Backend_Country': 'china',
        'Technology_Node': 'MEMS',
        'Plant_1_Name': 'Bosch',
        'Plant_2_Name': 'Bosch',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 350000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'LGA',
    },
    {
        'Part Number': 'TJA1463',
        'Supplier Name': 'NXP',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Transceiver',
        'Country of Manufacturing Plant 1': 'Germany',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 18,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 16,
        'Unit Price ($)': 2.90,
        'Specify Certification/Qualification': 'AEC-Q100',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'germany',
        'Backend_Country': 'malaysia',
        'Technology_Node': '130nm',
        'Plant_1_Name': 'NXP',
        'Plant_2_Name': 'NXP (ATMC)',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 600000,
        'Automotive_Grade': 'AEC-Q100',
        'Last_Price_Increase_Pct': 5,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SOP',
    },
    {
        'Part Number': 'GCM32ER71E106KA37',
        'Supplier Name': 'Murata',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'Philippines',
        'Country of Manufacturing Plant 3': 'Thailand',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 8,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 4,
        'Unit Price ($)': 0.08,
        'Specify Certification/Qualification': 'AEC-Q200',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'japan',
        'Backend_Country': 'philippines',
        'Technology_Node': '',
        'Plant_1_Name': 'Murata',
        'Plant_2_Name': 'Murata',
        'Plant_3_Name': 'Murata',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 4,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 1000000,
        'Automotive_Grade': 'AEC-Q200',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': '1206',
    },
    {
        'Part Number': 'PESD2CAN-U',
        'Supplier Name': 'Nexperia',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'Germany',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': 'Philippines',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 6,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 3,
        'Unit Price ($)': 0.12,
        'Specify Certification/Qualification': 'AEC-Q101',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'germany',
        'Backend_Country': 'malaysia',
        'Technology_Node': '',
        'Plant_1_Name': 'Nexperia',
        'Plant_2_Name': 'Nexperia',
        'Plant_3_Name': 'Nexperia',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 800000,
        'Automotive_Grade': 'AEC-Q101',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SOT-23',
    },
    {
        'Part Number': 'VLS252015HBX-1R0M',
        'Supplier Name': 'TDK',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'Thailand',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 8,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 3,
        'Unit Price ($)': 0.15,
        'Specify Certification/Qualification': 'AEC-Q200',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'japan',
        'Backend_Country': 'thailand',
        'Technology_Node': '',
        'Plant_1_Name': 'TDK',
        'Plant_2_Name': 'TDK',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 5,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 900000,
        'Automotive_Grade': 'AEC-Q200',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SMD',
    },
    {
        'Part Number': '5025781070',
        'Supplier Name': 'Molex',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Connector',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 6,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 2,
        'Unit Price ($)': 0.45,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'japan',
        'Backend_Country': 'china',
        'Technology_Node': '',
        'Plant_1_Name': 'Molex',
        'Plant_2_Name': 'Molex',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 500000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'Connector',
    },
    {
        'Part Number': '1-2141530-1-AUT',
        'Supplier Name': 'TE Connectivity',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Connector',
        'Country of Manufacturing Plant 1': 'Mexico',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': 'Germany',
        'Country of Manufacturing Plant 4': 'USA',
        'Supplier Lead Time (weeks)': 8,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 4,
        'Unit Price ($)': 0.85,
        'Specify Certification/Qualification': 'AEC-Q200',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'mexico',
        'Backend_Country': 'china',
        'Technology_Node': '',
        'Plant_1_Name': 'TE',
        'Plant_2_Name': 'TE',
        'Plant_3_Name': 'TE',
        'Plant_4_Name': 'TE',
        'EMS_Used': 'Y',
        'EMS_Name': 'Bosch',
        'EMS_Location': 'Germany',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'NRND',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 600000,
        'Automotive_Grade': 'AEC-Q200',
        'Last_Price_Increase_Pct': 15,
        'Allocation_Status': 'Normal',
        'Package_Type': 'Connector',
    },

    # ========== IOT BOARD COMPONENTS ==========
    {
        'Part Number': 'R9A07G044L23GBG',
        'Supplier Name': 'Renesas',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'MPU',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 20,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 24,
        'Unit Price ($)': 15.00,
        'Specify Certification/Qualification': 'IEC 62443',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'PMIC RAA215300, DDR3L AS4C256M16D3C',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'malaysia',
        'Technology_Node': '22nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'Amkor',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 4096,
        'Memory_Type': 'External',
        'OS_Type': 'Linux',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 350000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 10,
        'Allocation_Status': 'Normal',
        'Package_Type': 'BGA',
    },
    {
        'Part Number': 'RAA215300',
        'Supplier Name': 'Renesas',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Power',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 18,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 20,
        'Unit Price ($)': 3.50,
        'Specify Certification/Qualification': 'IEC 62443',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'R9A07G044L23GBG MPU',
        'Frontend_Country': 'japan',
        'Backend_Country': 'malaysia',
        'Technology_Node': '130nm',
        'Plant_1_Name': 'Renesas',
        'Plant_2_Name': 'Renesas',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 0,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 500000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 5,
        'Allocation_Status': 'Normal',
        'Package_Type': 'QFN',
    },
    {
        'Part Number': 'QCA6174A-5',
        'Supplier Name': 'Qualcomm',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Transceiver Wireless',
        'Country of Manufacturing Plant 1': 'Taiwan',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 22,
        'Proprietary (Y/N)**': 'Y',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 18,
        'Unit Price ($)': 8.90,
        'Specify Certification/Qualification': 'FCC, CE, TELEC',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'taiwan',
        'Backend_Country': 'china',
        'Technology_Node': '28nm',
        'Plant_1_Name': 'TSMC',
        'Plant_2_Name': 'ASE',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 2048,
        'Memory_Type': '',
        'OS_Type': 'Linux',
        'Wireless_Protocol': 'WiFi, BLE',
        'EOL_Status': 'NRND',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 300000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 25,
        'Allocation_Status': 'Constrained',
        'Package_Type': 'BGA',
    },
    {
        'Part Number': 'EC25-E',
        'Supplier Name': 'Quectel',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Transceiver Wireless',
        'Country of Manufacturing Plant 1': 'China',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 14,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 16,
        'Unit Price ($)': 18.50,
        'Specify Certification/Qualification': 'CE, FCC, PTCRB',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'china',
        'Backend_Country': 'china',
        'Technology_Node': '28nm',
        'Plant_1_Name': 'Qualcomm',
        'Plant_2_Name': 'Quectel',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 512,
        'Memory_Type': '',
        'OS_Type': 'Linux',
        'Wireless_Protocol': 'LTE',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'B',
        'MTBF_Hours': 200000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'Module',
    },
    {
        'Part Number': 'MT29F4G08ABAFAWP',
        'Supplier Name': 'Micron',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Memory',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'Singapore',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 16,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 8,
        'Unit Price ($)': 3.20,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'japan',
        'Backend_Country': 'singapore',
        'Technology_Node': '14nm',
        'Plant_1_Name': 'Micron',
        'Plant_2_Name': 'Micron',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Last_Buy',
        'Number_of_Alternative_Sources': 2,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 250000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 40,
        'Allocation_Status': 'Allocated',
        'Package_Type': 'TSOP',
    },
    {
        'Part Number': 'AS4C256M16D3C-12',
        'Supplier Name': 'Alliance Memory',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Memory',
        'Country of Manufacturing Plant 1': 'China',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 14,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'N',
        'Weeks to qualify': 12,
        'Unit Price ($)': 2.80,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': 'R9A07G044L23GBG MPU',
        'Frontend_Country': 'china',
        'Backend_Country': 'china',
        'Technology_Node': '25nm',
        'Plant_1_Name': 'SMIC',
        'Plant_2_Name': 'JCET',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': 'External',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'C',
        'MTBF_Hours': 200000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 18,
        'Allocation_Status': 'Normal',
        'Package_Type': 'BGA',
    },
    {
        'Part Number': 'LAN9250',
        'Supplier Name': 'Microchip',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Transceiver',
        'Country of Manufacturing Plant 1': 'USA',
        'Country of Manufacturing Plant 2': 'Thailand',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 28,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'N',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 14,
        'Unit Price ($)': 4.50,
        'Specify Certification/Qualification': 'IEC 62443',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'usa',
        'Backend_Country': 'thailand',
        'Technology_Node': '90nm',
        'Plant_1_Name': 'Microchip',
        'Plant_2_Name': 'Amkor',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 256,
        'Memory_Type': 'Embedded',
        'OS_Type': 'Linux',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 1,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 400000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 55,
        'Allocation_Status': 'Allocated',
        'Package_Type': 'QFP',
    },
    {
        'Part Number': 'Si7021-A20-GM1R',
        'Supplier Name': 'Silicon Labs',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Sensor',
        'Country of Manufacturing Plant 1': 'USA',
        'Country of Manufacturing Plant 2': 'Malaysia',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 10,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 6,
        'Unit Price ($)': 2.10,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'usa',
        'Backend_Country': 'malaysia',
        'Technology_Node': '180nm',
        'Plant_1_Name': 'Silicon Labs',
        'Plant_2_Name': 'ASE',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'EOL',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 300000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'DFN',
    },
    {
        'Part Number': 'C2012X7R1H104K',
        'Supplier Name': 'TDK',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'Japan',
        'Country of Manufacturing Plant 2': 'Philippines',
        'Country of Manufacturing Plant 3': 'China',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 6,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 2,
        'Unit Price ($)': 0.01,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'japan',
        'Backend_Country': 'philippines',
        'Technology_Node': '',
        'Plant_1_Name': 'TDK',
        'Plant_2_Name': 'TDK',
        'Plant_3_Name': 'TDK',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 5,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 1000000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': '0805',
    },
    {
        'Part Number': '744043100',
        'Supplier Name': 'Wurth Elektronik',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'Germany',
        'Country of Manufacturing Plant 2': 'Germany',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 10,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 4,
        'Unit Price ($)': 0.65,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'germany',
        'Backend_Country': 'germany',
        'Technology_Node': '',
        'Plant_1_Name': 'Wurth',
        'Plant_2_Name': 'Wurth',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 3,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 800000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SMD',
    },
    {
        'Part Number': '10118194-0001LF',
        'Supplier Name': 'Amphenol',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Connector',
        'Country of Manufacturing Plant 1': 'China',
        'Country of Manufacturing Plant 2': 'China',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 8,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 3,
        'Unit Price ($)': 0.55,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'china',
        'Backend_Country': 'china',
        'Technology_Node': '',
        'Plant_1_Name': 'Amphenol',
        'Plant_2_Name': 'Amphenol',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 4,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 500000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 5,
        'Allocation_Status': 'Normal',
        'Package_Type': 'USB-C',
    },
    {
        'Part Number': 'IHLP2525CZER1R0M11',
        'Supplier Name': 'Vishay',
        'Category of product (MCU, MPU, Sensor, Analogic, Power, Passive Component, Transceiver Wireless)': 'Passive Component',
        'Country of Manufacturing Plant 1': 'USA',
        'Country of Manufacturing Plant 2': 'Mexico',
        'Country of Manufacturing Plant 3': '',
        'Country of Manufacturing Plant 4': '',
        'Supplier Lead Time (weeks)': 8,
        'Proprietary (Y/N)**': 'N',
        'Commodity (Y/N)*': 'Y',
        'Stand-Alone Functional Device (Y/N)': 'Y',
        'Weeks to qualify': 3,
        'Unit Price ($)': 0.35,
        'Specify Certification/Qualification': '',
        'In case answer on Column C is Y, Which other device in the BOM is necessary to run the PN on Column B? (e.g. PMIC for MPU, Memory for MPU)': '',
        'Frontend_Country': 'usa',
        'Backend_Country': 'mexico',
        'Technology_Node': '',
        'Plant_1_Name': 'Vishay',
        'Plant_2_Name': 'Vishay',
        'Plant_3_Name': '',
        'Plant_4_Name': '',
        'EMS_Used': 'Y',
        'EMS_Name': 'Foxconn',
        'EMS_Location': 'China',
        'SW_Code_Size_KB': 0,
        'Memory_Type': '',
        'OS_Type': '',
        'Wireless_Protocol': '',
        'EOL_Status': 'Active',
        'Number_of_Alternative_Sources': 4,
        'Supplier_Financial_Health': 'A',
        'MTBF_Hours': 700000,
        'Automotive_Grade': '',
        'Last_Price_Increase_Pct': 0,
        'Allocation_Status': 'Normal',
        'Package_Type': 'SMD',
    },
]

# Dati Client_Data (quantità e buffer specifici per cliente)
CLIENT_DATA = {
    'ADAS_AUTO': [
        {'pn': 'S32K344', 'qty': 1, 'buffer': 75000},
        {'pn': 'S32G274A', 'qty': 1, 'buffer': 0},
        {'pn': 'PF5024', 'qty': 1, 'buffer': 15000},
        {'pn': 'EyeQ5H', 'qty': 1, 'buffer': 0},
        {'pn': 'MT53E256M32D1DS-046', 'qty': 4, 'buffer': 0},
        {'pn': 'MX25U25645G', 'qty': 2, 'buffer': 40000},
        {'pn': '88Q2112-A2-NNP2I000', 'qty': 2, 'buffer': 25000},
        {'pn': 'TPS65263-1QRGZRQ1', 'qty': 1, 'buffer': 80000},
        {'pn': 'SMI230', 'qty': 1, 'buffer': 30000},
        {'pn': 'TJA1463', 'qty': 3, 'buffer': 60000},
        {'pn': 'GCM32ER71E106KA37', 'qty': 65, 'buffer': 5000000},
        {'pn': 'PESD2CAN-U', 'qty': 6, 'buffer': 500000},
        {'pn': 'VLS252015HBX-1R0M', 'qty': 8, 'buffer': 800000},
        {'pn': '5025781070', 'qty': 4, 'buffer': 200000},
        {'pn': '1-2141530-1-AUT', 'qty': 2, 'buffer': 200000},
    ],
    'IOT_INDUST': [
        {'pn': 'R9A07G044L23GBG', 'qty': 1, 'buffer': 0},
        {'pn': 'RAA215300', 'qty': 1, 'buffer': 20000},
        {'pn': 'QCA6174A-5', 'qty': 1, 'buffer': 0},
        {'pn': 'EC25-E', 'qty': 1, 'buffer': 15000},
        {'pn': 'MT29F4G08ABAFAWP', 'qty': 1, 'buffer': 0},
        {'pn': 'AS4C256M16D3C-12', 'qty': 2, 'buffer': 30000},
        {'pn': 'LAN9250', 'qty': 1, 'buffer': 8000},
        {'pn': 'Si7021-A20-GM1R', 'qty': 1, 'buffer': 50000},
        {'pn': 'C2012X7R1H104K', 'qty': 120, 'buffer': 10000000},
        {'pn': '744043100', 'qty': 4, 'buffer': 150000},
        {'pn': '10118194-0001LF', 'qty': 2, 'buffer': 100000},
        {'pn': 'IHLP2525CZER1R0M11', 'qty': 6, 'buffer': 300000},
    ],
}


# =========================================================================
# FUNZIONI DI AGGIORNAMENTO
# =========================================================================

def update_database():
    """Aggiorna il database con tutti i nuovi part numbers."""
    print("Initializing database...")
    db = PartNumberDatabase('part_numbers_db.xlsx')

    # Migra database se necessario
    print("Migrating database schema...")
    db.migrate_database()

    # Aggiungi clienti
    print("\n=== Adding Clients ===")
    for client in CLIENTS:
        if db.add_client(client['Client_ID'], client['Client_Name'], client['Default_Run_Rate']):
            print(f"  Added client: {client['Client_ID']} - {client['Client_Name']}")
        else:
            print(f"  Client {client['Client_ID']} already exists or error")

    # Aggiungi part numbers
    print(f"\n=== Adding Part Numbers ({len(COMPONENTS_DB)} components) ===")
    for comp in COMPONENTS_DB:
        pn = comp['Part Number']
        if db.add_part_number(pn, comp):
            print(f"  Added: {pn} ({comp['Supplier Name']})")
        else:
            print(f"  Updated: {pn} ({comp['Supplier Name']})")

    # Aggiungi dati specifici per cliente
    print("\n=== Adding Client-Specific Data (qty, buffer) ===")
    for client_id, data_list in CLIENT_DATA.items():
        for item in data_list:
            pn = item['pn']
            qty = item['qty']
            buffer = item['buffer']

            client_data = {
                'How Many Device of this specific PN are in the BOM?': qty,
                'If Dedicated Buffer Stock Units to the supplier is yes specify the number of Units': buffer,
                'Custom Supplier Lead Time (weeks)': None,
                'Notes': f'Importato da BOM {client_id}',
            }

            if db.add_part_number(pn, client_data, client_id):
                print(f"  Added client data: {client_id} - {pn} (qty={qty}, buffer={buffer})")
            else:
                print(f"  Updated client data: {client_id} - {pn}")

    print("\n=== Database Update Complete ===")

    # Statistiche finali
    stats = db.get_stats()
    print(f"\nFinal Database Statistics:")
    print(f"  Total Part Numbers: {stats['total_part_numbers']}")
    print(f"  Total Clients: {stats['total_clients']}")
    print(f"  Total Client Records: {stats['total_client_records']}")


if __name__ == '__main__':
    update_database()
